### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by wn1099** [lmenezes/cerebro-docker#12]
Hi,

There is a Typo in Readme at `docker run -p 9000:9000 --network=host lmenez/cerebro`. It should be `docker run -p 9000:9000 --network=host lmenezes/cerebro`. 

Note **lmenezes** instead of **lmenez**.

Thanks

**Comment by lmenezes** [comment]
Wanna send a PR with the fix? :)

**Comment by wn1099** [comment]
Sure, please see PR#13
