### ISSUE TITLE
Support multi architecture

### ISSUE THREAD

**Issue by matthew-gill** [lmenezes/cerebro-docker#14]
👋  Thanks for this docker container!
Our team are multi architecture, a mixture of x86 and arm.

Would it be possible for you to tag and push a multi architecture version of this container so those of us on arm can make use of it?

I've noticed the most recent release: https://github.com/lmenezes/cerebro/releases/tag/v0.9.4 has a noarch rpm, and the base container `openjdk:11.0.10-jre-slim` supports both architectures:

![image](https://user-images.githubusercontent.com/31350541/121319425-1b4cc400-c904-11eb-8617-53cc9fce49a1.png)

If it helps, here's the command I use to build multi arch containers

```
docker buildx build --no-cache --platform linux/amd64,linux/arm64 -t your-repo/container:latest --push .
```

**Comment by gillg** [comment]
I need the same thing, I was ready to contribute but your build script is not versioned here.
Can you make the change on your pipeline in charge to build the image ?

**Comment by gillg** [comment]
Probably resolved by https://github.com/lmenezes/cerebro-docker/pull/15

**Comment by moliware** [comment]
For now you can use arm-compatible images from https://github.com/lmenezes/cerebro-docker/pkgs/container/cerebro-docker

I guess, in next tag there will be compatibility.  For current tag `0.9.4` I should remove and tag again to force docker hub to rebuild the image (I don't have permissions to push, so it has to be with the automatic process). I will try.

Thank you!
